[project]
name = "every-eval-ever"
version = "0.1.0"
description = "Every Eval Ever"
readme = "README.md"
authors = [
    { name = "EvalEval", email = "evalevalpc@googlegroups.com" }
]
requires-python = ">=3.12"
dependencies = [
    "jsonschema>=4.25.1",
]

[dependency-groups]
dev = [
    "pre-commit>=4.3.0",
]
