name: Validate data

on:
  push:
    branches: [ main ]
    paths:
      - 'utils/validate_data.py'
      - 'eval.schema.json'
      - 'data/**'
  pull_request:
    paths:
      - 'utils/validate_data.py'
      - 'eval.schema.json'
      - 'data/**'

jobs:
  validate-json:
    name: Validate data
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.9.4"
          # Disable cache because there are no requirements lockfiles
          enable-cache: false

      - name: Check for duplicate entries
        run: uv run python utils/check_duplicate_entries.py data

      - name: Validate data
        run: uv run pre-commit run --all-files
